//  Copyright (C) 2026 Nethesis S.r.l.
//  SPDX-License-Identifier: GPL-3.0-or-later

/**
 * Mock data for SystemChangesTimeline — pass mockMode prop to the component to
 * render with this data instead of live API calls.
 *
 * Timeline covers today (no changes) + ten historical groups spread across
 * four months, with notable gaps between them.  Diffs exercise every
 * combination of diff_type × severity × category and include scalar, boolean,
 * object, array, empty-string, and null values.
 */

import { type InventoryDiff } from './inventoryDiffs'
import { type InventoryTimelineGroup, type InventoryTimelineSummary } from './inventoryTimeline'
import { type Pagination } from '@/lib/common'

// ── Reference date ────────────────────────────────────────────────────────────
// The component always injects today's date dynamically, so these groups start
// from 2026-03-22 (yesterday).

// ── Timeline summary ──────────────────────────────────────────────────────────
export const mockTimelineSummary: InventoryTimelineSummary = {
  total: 35,
  critical: 6,
  high: 8,
  medium: 7,
  low: 14,
}

// ── Timeline groups ───────────────────────────────────────────────────────────
// Layout (newest → oldest):
//
//  2026-03-22  yesterday      3 changes   inventory_ids: 101–103
//  2026-03-21  2 days ago     1 change    inventory_ids: 104
//  2026-03-18  5 days ago     5 changes   inventory_ids: 105–109   (gap: 2 days)
//  2026-03-13  10 days ago    2 changes   inventory_ids: 110–111   (gap: 4 days)
//  2026-03-01  22 days ago    4 changes   inventory_ids: 112–115   (gap: 11 days)
//  2026-02-15  36 days ago    4 changes   inventory_ids: 116–119   (gap: 14 days)
//  2026-02-01  50 days ago    3 changes   inventory_ids: 120–122   (gap: 14 days)
//  2026-01-18  64 days ago    5 changes   inventory_ids: 123–127   (gap: 14 days)
//  2026-01-05  77 days ago    2 changes   inventory_ids: 128–129   (gap: 13 days)
//  2025-12-22  91 days ago    6 changes   inventory_ids: 130–135   (gap: 14 days)
export const mockTimelineGroups: InventoryTimelineGroup[] = [
  {
    date: '2026-03-22',
    inventory_count: 3,
    change_count: 3,
    inventory_ids: [101, 102, 103],
  },
  {
    date: '2026-03-21',
    inventory_count: 1,
    change_count: 1,
    inventory_ids: [104],
  },
  {
    date: '2026-03-18',
    inventory_count: 5,
    change_count: 5,
    inventory_ids: [105, 106, 107, 108, 109],
  },
  {
    date: '2026-03-13',
    inventory_count: 2,
    change_count: 2,
    inventory_ids: [110, 111],
  },
  {
    date: '2026-03-01',
    inventory_count: 4,
    change_count: 4,
    inventory_ids: [112, 113, 114, 115],
  },
  {
    date: '2026-02-15',
    inventory_count: 4,
    change_count: 4,
    inventory_ids: [116, 117, 118, 119],
  },
  {
    date: '2026-02-01',
    inventory_count: 3,
    change_count: 3,
    inventory_ids: [120, 121, 122],
  },
  {
    date: '2026-01-18',
    inventory_count: 5,
    change_count: 5,
    inventory_ids: [123, 124, 125, 126, 127],
  },
  {
    date: '2026-01-05',
    inventory_count: 2,
    change_count: 2,
    inventory_ids: [128, 129],
  },
  {
    date: '2025-12-22',
    inventory_count: 6,
    change_count: 6,
    inventory_ids: [130, 131, 132, 133, 134, 135],
  },
]

export const mockTimelinePagination: Pagination = {
  page: 1,
  page_size: 10,
  total_count: 10,
  total_pages: 1,
  has_next: false,
  has_prev: false,
}

// ── Inventory diffs ───────────────────────────────────────────────────────────
// 15 diffs covering every diff_type × severity combination and all 10 categories.

export const mockInventoryDiffs: InventoryDiff[] = [
  // ── 2026-03-22 (inventory_ids 101–103) ──────────────────────────────────────
  {
    id: 1,
    system_id: 'sys-demo-001',
    previous_inventory_id: 100,
    inventory_id: 101,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.kernel_version',
    previous_value: '5.15.0-89-generic',
    current_value: '5.15.0-91-generic',
    severity: 'low',
    notification_sent: false,
    created_at: '2026-03-22T08:14:02Z',
  },
  {
    id: 2,
    system_id: 'sys-demo-001',
    previous_inventory_id: 100,
    inventory_id: 102,
    diff_type: 'create',
    category: 'security',
    field_path: 'security.firewall_rules[12]',
    previous_value: null,
    current_value: { port: 22, protocol: 'tcp', action: 'ACCEPT', source: '10.0.0.0/8' },
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-03-22T09:31:45Z',
  },
  {
    id: 3,
    system_id: 'sys-demo-001',
    previous_inventory_id: 100,
    inventory_id: 103,
    diff_type: 'delete',
    category: 'network',
    field_path: 'network.interfaces.eth1',
    previous_value: { ip: '192.168.1.50', netmask: '255.255.255.0', mtu: 1500 },
    current_value: null,
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-03-22T11:05:19Z',
  },

  // ── 2026-03-21 (inventory_id 104) ───────────────────────────────────────────
  {
    id: 4,
    system_id: 'sys-demo-001',
    previous_inventory_id: 103,
    inventory_id: 104,
    diff_type: 'update',
    category: 'hardware',
    field_path: 'hardware.cpu.cores',
    previous_value: 4,
    current_value: 8,
    severity: 'high',
    notification_sent: true,
    created_at: '2026-03-21T14:22:00Z',
  },

  // ── 2026-03-18 (inventory_ids 105–109) ──────────────────────────────────────
  {
    id: 5,
    system_id: 'sys-demo-001',
    previous_inventory_id: 104,
    inventory_id: 105,
    diff_type: 'create',
    category: 'modules',
    field_path: 'modules[7]',
    previous_value: null,
    current_value: { name: 'nethserver-fail2ban', version: '1.2.3', active: true },
    severity: 'low',
    notification_sent: false,
    created_at: '2026-03-18T06:00:01Z',
  },
  {
    id: 6,
    system_id: 'sys-demo-001',
    previous_inventory_id: 104,
    inventory_id: 106,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.version',
    previous_value: 'NethServer 7.9.2009',
    current_value: 'NethServer 8.1',
    severity: 'high',
    notification_sent: true,
    created_at: '2026-03-18T06:05:33Z',
  },
  {
    id: 7,
    system_id: 'sys-demo-001',
    previous_inventory_id: 104,
    inventory_id: 107,
    diff_type: 'delete',
    category: 'backup',
    field_path: 'backup.jobs.nightly_db',
    previous_value: { schedule: '0 2 * * *', destination: '/mnt/nas/backup', retention: 7 },
    current_value: null,
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-03-18T06:10:11Z',
  },
  {
    id: 8,
    system_id: 'sys-demo-001',
    previous_inventory_id: 104,
    inventory_id: 108,
    diff_type: 'create',
    category: 'cluster',
    field_path: 'cluster.nodes[2]',
    previous_value: null,
    current_value: { name: 'node3', role: 'worker', ip: '10.0.0.3', joined_at: '2026-03-18' },
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-03-18T07:45:55Z',
  },
  {
    id: 9,
    system_id: 'sys-demo-001',
    previous_inventory_id: 104,
    inventory_id: 109,
    diff_type: 'update',
    category: 'features',
    field_path: 'features.mail.enabled',
    previous_value: false,
    current_value: true,
    severity: 'low',
    notification_sent: false,
    created_at: '2026-03-18T09:12:40Z',
  },

  // ── 2026-03-13 (inventory_ids 110–111) ──────────────────────────────────────
  {
    id: 10,
    system_id: 'sys-demo-001',
    previous_inventory_id: 109,
    inventory_id: 110,
    diff_type: 'update',
    category: 'system',
    field_path: 'system.hostname',
    previous_value: 'server01.example.com',
    current_value: 'firewall.acme.corp',
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-03-13T16:03:27Z',
  },
  {
    id: 11,
    system_id: 'sys-demo-001',
    previous_inventory_id: 109,
    inventory_id: 111,
    diff_type: 'delete',
    category: 'nodes',
    field_path: 'nodes[1]',
    previous_value: { name: 'worker-2', status: 'active', cpu_cores: 8, ram_gb: 32 },
    current_value: null,
    severity: 'high',
    notification_sent: true,
    created_at: '2026-03-13T17:55:09Z',
  },

  // ── 2026-03-01 (inventory_ids 112–115) ──────────────────────────────────────
  {
    id: 12,
    system_id: 'sys-demo-001',
    previous_inventory_id: 111,
    inventory_id: 112,
    diff_type: 'create',
    category: 'network',
    field_path: 'network.bonding.bond0',
    previous_value: null,
    current_value: { mode: 'active-backup', slaves: ['eth0', 'eth1'], mtu: 9000 },
    severity: 'low',
    notification_sent: false,
    created_at: '2026-03-01T02:00:00Z',
  },
  {
    id: 13,
    system_id: 'sys-demo-001',
    previous_inventory_id: 111,
    inventory_id: 113,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.packages_update_count',
    previous_value: 0,
    current_value: 42,
    severity: 'high',
    notification_sent: true,
    created_at: '2026-03-01T02:05:14Z',
  },
  {
    id: 14,
    system_id: 'sys-demo-001',
    previous_inventory_id: 111,
    inventory_id: 114,
    diff_type: 'update',
    category: 'security',
    field_path: 'security.certificates.web.expiry_days',
    previous_value: 90,
    current_value: 7,
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-03-01T02:10:30Z',
  },
  {
    id: 15,
    system_id: 'sys-demo-001',
    previous_inventory_id: 111,
    inventory_id: 115,
    diff_type: 'create',
    category: 'features',
    field_path: 'features.vpn.wireguard',
    previous_value: null,
    current_value: { enabled: true, port: 51820, peers: 3 },
    severity: 'low',
    notification_sent: false,
    created_at: '2026-03-01T03:30:00Z',
  },

  // ── 2026-02-15 (inventory_ids 116–119) ──────────────────────────────────────
  {
    id: 16,
    system_id: 'sys-demo-001',
    previous_inventory_id: 115,
    inventory_id: 116,
    diff_type: 'create',
    category: 'os',
    field_path: 'os.swap_enabled',
    previous_value: null,
    current_value: false,
    severity: 'low',
    notification_sent: false,
    created_at: '2026-02-15T03:10:00Z',
  },
  {
    id: 17,
    system_id: 'sys-demo-001',
    previous_inventory_id: 115,
    inventory_id: 117,
    diff_type: 'update',
    category: 'network',
    field_path: 'network.dns_servers',
    previous_value: ['1.1.1.1'],
    current_value: ['8.8.8.8', '8.8.4.4', '1.1.1.1'],
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-02-15T03:15:22Z',
  },
  {
    id: 18,
    system_id: 'sys-demo-001',
    previous_inventory_id: 115,
    inventory_id: 118,
    diff_type: 'delete',
    category: 'security',
    field_path: 'security.users.admin.authorized_keys[0]',
    previous_value: { key: 'ssh-rsa AAAAB3NzaC1yc2E...', comment: 'old-laptop', bits: 2048 },
    current_value: null,
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-02-15T08:44:11Z',
  },
  {
    id: 19,
    system_id: 'sys-demo-001',
    previous_inventory_id: 115,
    inventory_id: 119,
    diff_type: 'update',
    category: 'hardware',
    field_path: 'hardware.memory.total_gb',
    previous_value: 16,
    current_value: 32,
    severity: 'low',
    notification_sent: false,
    created_at: '2026-02-15T10:00:00Z',
  },

  // ── 2026-02-01 (inventory_ids 120–122) ──────────────────────────────────────
  {
    id: 20,
    system_id: 'sys-demo-001',
    previous_inventory_id: 119,
    inventory_id: 120,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.timezone',
    previous_value: 'UTC',
    current_value: 'Europe/Rome',
    severity: 'low',
    notification_sent: false,
    created_at: '2026-02-01T09:00:00Z',
  },
  {
    id: 21,
    system_id: 'sys-demo-001',
    previous_inventory_id: 119,
    inventory_id: 121,
    diff_type: 'create',
    category: 'modules',
    field_path: 'modules[8]',
    previous_value: null,
    current_value: { name: 'nethserver-mail-server', version: '2.4.1', active: true },
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-02-01T11:22:33Z',
  },
  {
    id: 22,
    system_id: 'sys-demo-001',
    previous_inventory_id: 119,
    inventory_id: 122,
    diff_type: 'delete',
    category: 'cluster',
    field_path: 'cluster.virtual_ip',
    previous_value: { ip: '10.0.0.100', interface: 'eth0', check_interval_ms: 500 },
    current_value: null,
    severity: 'high',
    notification_sent: true,
    created_at: '2026-02-01T14:55:00Z',
  },

  // ── 2026-01-18 (inventory_ids 123–127) ──────────────────────────────────────
  {
    id: 23,
    system_id: 'sys-demo-001',
    previous_inventory_id: 122,
    inventory_id: 123,
    diff_type: 'update',
    category: 'system',
    field_path: 'system.fqdn',
    previous_value: 'old.server.local',
    current_value: 'prod-fw.acme.corp',
    severity: 'medium',
    notification_sent: false,
    created_at: '2026-01-18T07:01:00Z',
  },
  {
    id: 24,
    system_id: 'sys-demo-001',
    previous_inventory_id: 122,
    inventory_id: 124,
    diff_type: 'create',
    category: 'network',
    field_path: 'network.vlans.vlan10',
    previous_value: null,
    current_value: { id: 10, name: 'DMZ', interface: 'eth0.10', tagged: true },
    severity: 'low',
    notification_sent: false,
    created_at: '2026-01-18T07:30:45Z',
  },
  {
    id: 25,
    system_id: 'sys-demo-001',
    previous_inventory_id: 122,
    inventory_id: 125,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.selinux_status',
    previous_value: 'enforcing',
    current_value: 'permissive',
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-01-18T09:15:00Z',
  },
  {
    id: 26,
    system_id: 'sys-demo-001',
    previous_inventory_id: 122,
    inventory_id: 126,
    diff_type: 'delete',
    category: 'backup',
    field_path: 'backup.jobs.weekly_full',
    previous_value: { schedule: '0 0 * * 0', destination: 's3://mybucket/weekly', retention: 4 },
    current_value: null,
    severity: 'high',
    notification_sent: true,
    created_at: '2026-01-18T10:00:00Z',
  },
  {
    id: 27,
    system_id: 'sys-demo-001',
    previous_inventory_id: 122,
    inventory_id: 127,
    diff_type: 'update',
    category: 'features',
    field_path: 'features.antivirus.signatures_date',
    previous_value: '2025-01-10',
    current_value: '2026-01-18',
    severity: 'low',
    notification_sent: false,
    created_at: '2026-01-18T12:00:00Z',
  },

  // ── 2026-01-05 (inventory_ids 128–129) ──────────────────────────────────────
  {
    id: 28,
    system_id: 'sys-demo-001',
    previous_inventory_id: 127,
    inventory_id: 128,
    diff_type: 'update',
    category: 'hardware',
    field_path: 'hardware.disk.sda.health',
    previous_value: 'OK',
    current_value: 'WARN',
    severity: 'critical',
    notification_sent: true,
    created_at: '2026-01-05T04:00:00Z',
  },
  {
    id: 29,
    system_id: 'sys-demo-001',
    previous_inventory_id: 127,
    inventory_id: 129,
    diff_type: 'update',
    category: 'nodes',
    field_path: 'nodes[0].status',
    previous_value: 'active',
    current_value: 'maintenance',
    severity: 'high',
    notification_sent: true,
    created_at: '2026-01-05T06:30:00Z',
  },

  // ── 2025-12-22 (inventory_ids 130–135) ──────────────────────────────────────
  {
    id: 30,
    system_id: 'sys-demo-001',
    previous_inventory_id: 129,
    inventory_id: 130,
    diff_type: 'create',
    category: 'security',
    field_path: 'security.openvpn.certificates[0]',
    previous_value: null,
    current_value: { cn: 'vpn-user1', expiry: '2027-12-22', bits: 4096 },
    severity: 'low',
    notification_sent: false,
    created_at: '2025-12-22T01:00:00Z',
  },
  {
    id: 31,
    system_id: 'sys-demo-001',
    previous_inventory_id: 129,
    inventory_id: 131,
    diff_type: 'update',
    category: 'os',
    field_path: 'os.packages_update_count',
    // edge: number going back to zero
    previous_value: 23,
    current_value: 0,
    severity: 'low',
    notification_sent: false,
    created_at: '2025-12-22T02:00:00Z',
  },
  {
    id: 32,
    system_id: 'sys-demo-001',
    previous_inventory_id: 129,
    inventory_id: 132,
    diff_type: 'delete',
    category: 'network',
    field_path: 'network.routes.192.168.99.0/24',
    previous_value: { gateway: '10.0.0.1', metric: 100, proto: 'static' },
    current_value: null,
    severity: 'medium',
    notification_sent: false,
    created_at: '2025-12-22T03:10:00Z',
  },
  {
    id: 33,
    system_id: 'sys-demo-001',
    previous_inventory_id: 129,
    inventory_id: 133,
    diff_type: 'update',
    category: 'system',
    field_path: 'system.ssh_port',
    previous_value: 22,
    current_value: 2222,
    severity: 'high',
    notification_sent: true,
    created_at: '2025-12-22T04:00:00Z',
  },
  {
    id: 34,
    system_id: 'sys-demo-001',
    previous_inventory_id: 129,
    inventory_id: 134,
    diff_type: 'update',
    category: 'hardware',
    field_path: 'hardware.cpu.model',
    // edge: empty string → non-empty (renders as '—' → value)
    previous_value: '',
    current_value: 'Intel Core i9-13900K @ 3.00GHz',
    severity: 'low',
    notification_sent: false,
    created_at: '2025-12-22T05:00:00Z',
  },
  {
    id: 35,
    system_id: 'sys-demo-001',
    // edge: very first inventory snapshot — no previous
    previous_inventory_id: null,
    inventory_id: 135,
    diff_type: 'create',
    category: 'os',
    field_path: 'os.installation_date',
    previous_value: null,
    current_value: '2025-12-22',
    severity: 'low',
    notification_sent: false,
    created_at: '2025-12-22T06:00:00Z',
  },
]

export const mockDiffsPagination: Pagination = {
  page: 1,
  page_size: 500,
  total_count: 35,
  total_pages: 1,
  has_next: false,
  has_prev: false,
}
